<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/OpenKO.Common/OpenKO.Common.csproj" />
    <ProjectReference Include="../../src/OpenKO.Numerics/OpenKO.Numerics.csproj" />
    <ProjectReference Include="../../src/OpenKO.IO/OpenKO.IO.csproj" />
    <ProjectReference Include="../../src/OpenKO.N3/OpenKO.N3.csproj" />
    <ProjectReference Include="../../src/OpenKO.Net/OpenKO.Net.csproj" />
    <ProjectReference Include="..\..\src\OpenKO.Game\OpenKO.Game.csproj" />
  </ItemGroup>

</Project>
