<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenKO.Core\OpenKO.Core.csproj" />
    <ProjectReference Include="..\..\src\OpenKO.Network\OpenKO.Network.csproj" />
  </ItemGroup>

</Project>
