<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OpenKO.IO</RootNamespace>
    <AssemblyName>OpenKO.IO</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../OpenKO.Common/OpenKO.Common.csproj" />
  </ItemGroup>

</Project>
