<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servers\OpenKO.Servers.VersionManager\OpenKO.Servers.VersionManager.csproj" />
    <ProjectReference Include="..\..\src\Servers\OpenKO.Servers.ItemManager\OpenKO.Servers.ItemManager.csproj" />
    <ProjectReference Include="..\..\src\Servers\OpenKO.Servers.Aujard\OpenKO.Servers.Aujard.csproj" />
    <ProjectReference Include="..\..\src\Servers\OpenKO.Servers.AIServer\OpenKO.Servers.AIServer.csproj" />
    <ProjectReference Include="..\..\src\Servers\OpenKO.Servers.Ebenezer\OpenKO.Servers.Ebenezer.csproj" />
    <ProjectReference Include="..\..\tools\OpenKO.TestClient\OpenKO.TestClient.csproj" />
  </ItemGroup>

</Project>
